var typed = new Typed('.destaque', {
    strings: [
      'O melhor dia é aquele bem aproveitado.',
      'Desfrute a beleza da vida, viva o aqui e agora.',
      'Bem-vindo a oportunidade de renovar suas energias.',
      'Sorria! Você está no paraíso.',
      'Eu descanso para curtir melhor a vida.',
      'Não guarde rancor, guarde dinheiro para viajar.',
      'Todo mundo merece um descanso, venha aproveitar!',
      'Todos os caminhos da felicidade te trazem aqui.',
      'Viajar é o melhor dos investimentos.',
      'Aqui é o lugar para o seu descanso.',
      'Colecione bons momentos com a gente.',
      'Viajar também é uma maneira de autocuidado.',
    ],
    stringsElement: null,
    typeSpeed: 10,
    shuffle: true,
    loop: true,
    backDelay: 3000,
  })